;DesktopWorld settings

[connect default]
;disable unknown connect values
Access=NoAccess

[sql default]
;disable unknown sql values
Sql=" "

[connect DesktopWorldPages]
Access=ReadWrite
Connect="DSN=DesktopWorldPages"

[sql GetUserPage]
Sql="SELECT * FROM pages WHERE avatarName = ?"

[connect DesktopWorldBBS]
Access=ReadWrite
Connect="DSN=DesktopWorldBBS"

[sql getMessages]
sql="SELECT * FROM Messages ORDER BY Title ASC, CreateDate DESC"

[sql getNewMessages]
sql="SELECT * FROM qGetNewMessages"

[sql getTopics]
sql="SELECT * FROM qGetTopics"

[sql expandTopic]
sql="SELECT * FROM qExpandTopic WHERE (TopicId = ?) OR (MessageId = ?)"

[sql getMessageById]
sql="SELECT Content FROM Messages WHERE MessageId = ?"
