<%@ Language=VBScript %>

<%
' --------------
' login.asp
' --------------
' Collect user info and start the sample world client.
' This page invokes itself to save user info in the database and start the client.

option explicit

%>
<!-- #include FILE = ../vbs/pathnames.vbs -->
<%

dim isValidUser, formMode
dim gotoURL		' server-side var to contain world location;
				' sent to client-side script via a gotoURL input field on the page
isValidUser = false
formMode = Request("hidFormMode")
username = Request("hidUsername")
password = Request("txtPassword")
if formMode = "connect" then
	dim username, password
	dim conn, rs
	set conn = server.CreateObject ("ADODB.Connection")
	conn.open "DesktopWorldPages"
	set rs = conn.Execute ("SELECT * FROM pages WHERE AvatarName='" & username & "'")
	if rs.EOF then	' this username does not exist yet, so add it and connect to the world
		conn.Execute ("INSERT INTO pages (AvatarName,Password,DateModified) VALUES ('" & username & "','" & password & "','" & Now & "')")
		isValidUser = true
	elseif lcase(password) = lcase(rs("password")) then
		' user entered the correct password
		isValidUser = true
	end if
end if

if isValidUser then
	' Generate a URL that opens client.htm on the user's machine and tells it where the world is.
	' The client-side path to client.htm is sent by launcher.htm.
	' The world location is in a server-side include file ../vbs/pathnames.vbs.
	' This URL gets loaded into a goToURL field on the page when we generate the HTML below.
	' The page's window_onload reads this value and opens the client page.
	goToURL = "file://" & Request("clientPath") & "client.htm?" & Request("hidWorldLocation") & request("worldNum") & "&" & username
%>
<!-- Redirect to the client page in a new window (because it is a different size) -->
<html>
<head>
<script language="VBScript">
sub window_onLoad
	' get the URL generated by the ASP code and open the client page;
	' center the page in the available screen space if possible, or at the top left
	dim winHeight,winWidth,winTop,winLeft
	winHeight = window.screen.availHeight - 30
	if winHeight > 600 then winHeight = 600
	winWidth = window.screen.availWidth
	if winWidth > 790 then winWidth = 790
	winTop = (window.screen.availHeight - 600) / 2
	if winTop < 0 then winTop = 0
	winLeft = (window.screen.availWidth - 800) / 2
	if winLeft < 0 then winLeft = 0
	window.open theForm.gotoURL.value, "null", _
		"toolbar=no,location=no,menubar=no,status=no,resizable=yes," &_
		",height=" & winHeight &_
		",width=" & winWidth &_
		",top=" & winTop &_
		",left=" & winLeft
	window.close
end sub

function minOf(v1, v2)
	if v1 <= v2 then
		minOf = v1
	else
		minOf = v2
	end if
end function

function maxOf(v1, v2)
	if v1 >= v2 then
		maxOf = v1
	else
		maxOf = v2
	end if
end function
</script>
</head>
<body>
<form id=theForm action=Login.asp method=post>
<!-- this field is read by the window_onload script to determine how to connect to the world -->
<input type=hidden id="gotoURL" name="gotoURL" value="<%=gotoURL%>">
</form>
</body>
</html>

<% else
%>

<!-- Display the login page -->
<html>
<head>
<bgsound id=errSound>
<title>Login</title>
<link rel="stylesheet" href="../shared/global.css">
<style type=text/css>
H1 {font-family:verdana;font-size:10pt;font-style:italic;color:white;}
BUTTON {font-family:Tahoma; font-size:8pt; font-weight:normal; color:black; background-color:White;}
.LoginTextLight {font-family:verdana;font-size:9pt;font-style:normal;color:white;}
.LoginTextSmall {font-family:verdana;font-size:7pt;font-style:normal;color:white;}
.grayableButton {filter:light}
</style>

<object id="theclient" classid="clsid:D4898803-20EF-11D0-8A96-00A0C9082583"></object>
<!-- AvatarAccessControl gives us access to the avatars stored on the client's machine -->
<object id="AvatarAccessControl" classid="clsid:AF0AD5CC-418B-11D1-BB2B-00C04FC2CAB1"></object>
<script language="vbs">

option explicit

const defaultAvatarName = "(new name)"

sub window_OnLoad
	set avatarAccessControl.VWClient = theclient.vwclient
	refreshavatarList
	if screen.width < 800 or screen.height < 600 then
		msgbox "The world may not display properly at resolutions less than 800x600.", vbExclamation, "DesktopWorld"
	end if
	dim n, worldCount, element
	worldCount = CInt(theForm.hidWorldCount.value)
	for n = 1 to worldCount
		set element = document.createElement("OPTION")
		element.value = CStr(n)
		element.text = CStr(n)
		theForm.worldNum.add element, -1, element.text
	next
	if theForm.avatarList.length <= 1 then
		showError "To enter the world you must create a nickname."
		showCreateAvatarDialog
	else
		' restore selected name if there is one
		theForm.hidUsername.value = theForm.avatarList.value
		doAvatarSelected
	end if
	theForm.txtPassword.focus
	setDeleteButton
	if theForm.hidFormMode.value = "connect" then
		' we tried to connect but the user/pwd was not valid
		showError "Please enter a valid username and password"
	end if
end sub

sub window_OnUnload
	on error resume next
	dim VWClient
	set avatarAccessControl.VWClient = Nothing
	set VWClient = theclient.VWClient
	if Not VWClient Is Nothing then
		if Not VWClient.World Is Nothing then
			VWClient.World.disconnect
		end if
		VWClient.Disconnect
	end if
end sub

'===========================================
' DeleteBrokenAvatar
' remove a non-functioning avatar from the stored list on the client
sub DeleteBrokenAvatar(deadName)
	dim theResult, iCurAvatar
	iCurAvatar = theForm.avatarList.selectedIndex
	theResult = avatarAccessControl.deleteDeadAvatar(deadName)
	if theResult = true then
		refreshavatarList
		'Set current avatar to be the next one on the list
		'If the deleted avatar was the last one, select the first of element of the list
		if iCurAvatar < theForm.avatarList.Length - 1 then
			theForm.avatarList.selectedIndex = iCurAvatar
		else
			theForm.avatarList.selectedIndex = 0
		end if
		doAvatarSelected
	else
		showError "VWorlds could not delete this nickname" & vbcrlf & "due to an internal problem."
		avatarAccessControl.disconnectAvatar
	end if
end sub

'===========================================
' OnConfirmDelete
' Called by the Delete Avatar dialog
sub OnConfirmDelete
	dim iCurAvatar
	iCurAvatar = theForm.avatarList.selectedIndex
	avatarAccessControl.DeleteAvatar
	refreshavatarList
	'Set current avatar to be the next one on the list
	'If the deleted avatar was the last one, select the first of element of the list
	if iCurAvatar < theForm.avatarList.Length - 1 then
		theForm.avatarList.selectedIndex = iCurAvatar
	else
		theForm.avatarList.selectedIndex = 0
	end if
	doAvatarSelected
end sub

'===========================================
' OnDeleteAvatar
' Deletes that avatar from the list
sub OnDeleteAvatar
	if not theForm.btnDelete.disabled then window.showModalDialog "DeleteAvatar.htm", window, "dialogHeight:94px;dialogWidth:335px;help:no;status:no;"
end sub

'===========================================
' btnGo_onClick
' Connects this avatar to the world
Sub GoClick
	' Validate the avatar name
	if (trim(theForm.avatarList.value) = defaultAvatarName) or (trim(theForm.avatarList.value) = "") then
		theForm.avatarList.focus
		showError "Please select a name for yourself."
	elseif theForm.txtPassword.value = "" then 
		theForm.txtPassword.value = ""
		theForm.txtPassword.focus
		showError "Please enter a password."
	elseif getGender = "" then
		showError "Please select Male or Female."
	else
		saveProfileValues
		theForm.hidUsername.value = theForm.avatarList.value
		theForm.hidFormMode.value = "connect"
		theForm.submit
	end if
	window.event.returnValue = false	' or else for some reason it bubbles to btnDelete
end sub

'===========================================
' showError
' display a message in the error div at the top of the page
sub showError (msg)
	errSound.src = "../images/error.wav"
	errMsg.innerHTML = msg
	errMsg.style.display = "block"
end sub

sub clearErrMsg
	if errMsg.innerHTML > "" then
		errMsg.innerHTML = ""
		errMsg.style.display = "none"
	end if
end sub

sub document_onkeypress
	clearErrMsg
	if window.event.keycode = 13 then goClick
end sub

sub document_onMouseDown
	if mid(window.event.srcElement.id,1,3) <> "btn" then clearErrMsg
end sub

sub helpClick
	window.showModalDialog "loginHelp.htm", window, "dialogHeight:350px;dialogWidth:420px;help:no;status:no;"
end sub

function getGender
	if theForm.sexFemale.checked then
		getGender = "female"
	elseif theForm.sexMale.checked then
		getGender = "male"
	else
		getGender = ""
	end if
end function

'===========================================
' CreateAvatar
' Called by the new-avatar ASP;
' creates a new avatar, refreshes the avatar list and selects the new avatar.
sub CreateAvatar (avatarName, password, msg)
	dim isInSelectList, n
	msg = ""
	' see if the user name already exists
	isInSelectList = false
	for n = 0 to theForm.avatarList.length - 1
		if theForm.avatarList.options(n).value = avatarName then
			isInSelectList = true
			exit for
		end if
	next
	if isInSelectList then
		msg = "This nickname has already been used. Please enter a different name."
	elseif avatarAccessControl.createNewAvatar(avatarName, "") then
		AvatarAccessControl.ConnectAvatar avatarName, password
		refreshavatarList
		theForm.avatarList.value = avatarName
		theForm.txtPassword.value = password
		getProfileValues
		theForm.sexMale.focus
	else
		msg = "Unable to save this name.  Try using a different name.  If this error persists, check your sample world installation."
	end if
end sub

'===========================================
' CancelCreateAvatar
' Called by the new-avatar ASP when the user cancels;
' change the current avatar selection so clicking "new avatar" will retrigger onChange
sub CancelCreateAvatar
'	theForm.avatarList.selectedIndex = -1
	RefreshavatarList
end sub

'===========================================
' doAvatarSelected
' if an avatar is selected then load that avatar's data into the page
sub doAvatarSelected
	if trim(theForm.avatarList.value) <> defaultAvatarName then
		if avatarAccessControl.connectAvatar(theForm.avatarList.value, "") = false then
			msgbox "The selected nickname could not be loaded due to an internal problem."
			deleteBrokenAvatar theForm.avatarList.value
		end if
	end if
	getProfileValues
	setDeleteButton
end sub

'===========================================
' RefreshavatarList
' repopulate the avatar dropdown from the access control's list
sub RefreshavatarList
	dim element, avName, i, currentName
	for i = 0 to theForm.avatarList.length
		theForm.avatarList.remove(0)
	next
	for each avName in avatarAccessControl.avatarList
		set element = document.createElement("OPTION")
		element.value = avName
		element.text = avName
		theForm.avatarList.add element, posInList(theForm.avatarList, element.text)
	next
	'Restore the user's most recent name selection if possible
	currentName = theForm.hidUsername.value
	for i = 0 to theForm.avatarList.length - 1
		if theForm.avatarList.options(i).value = currentName then
			theForm.avatarList.selectedIndex = i
			exit for
		end if
	next
	'Last, create default new user entry
	set element = document.createElement("OPTION")
	element.value = defaultAvatarName
	element.text = defaultAvatarName
	theForm.avatarList.add element
end sub

function posInList(tagName, sItem)
	dim i
	PosInList = tagName.length
	for i = 0 to tagName.length - 1
		if lcase(sItem) < lcase(tagName.options.item(i).text) then
			posInList = i
			exit for
		end if
	next
end function

'===========================================
' showCreateAvatarDialog
sub showCreateAvatarDialog
	theForm.sexMale.checked = false
	theForm.sexFemale.checked = false
	hidFrame.navigate "CreateAvatar.asp"
end sub

'===========================================
' setDeleteButton
' Disable the delete button when "new avatar" is selected
sub setDeleteButton
	theForm.btnDelete.disabled = (theForm.avatarList.selectedIndex = theForm.avatarList.options.length - 1)
end sub

'===========================================
' avatarList_OnChange
' Called when the user changes the avatar dropdown selection
sub avatarList_OnChange
	' called when the user changes the avatar dropdown, or when we programmatically create or delete an avatar.
	if theForm.avatarList.selectedIndex = theForm.avatarList.options.length - 1 then
		showCreateAvatarDialog
		setDeleteButton
	else
		doAvatarSelected
	end if
end sub

'===========================================
' avatarList_OnClick
sub avatarList_OnClick
	' If there is only entry it will be "new name", so we want to add a name.
	' Note: onClick happens even if you just click on the dropdown arrow button,
	' so we don't want to call doAvatarSelected here.
	if theForm.avatarList.length = 1 then showCreateAvatarDialog
end sub

'===========================================
' document_OnClick
sub document_OnClick
	' If the user clicks on the background with the Ctrl and Shift keys held down,
	' display a dialog to enter the world location.
	if window.event.ctrlKey and window.event.shiftKey then
		theForm.hidWorldLocation.value = prompt ("VWorlds location (server/world)", theForm.hidWorldLocation.value)
	end if
end sub

'===========================================
' getProfileKey
' Get the value and access of an avatar profile key, creating the key if necessary
function getProfileKey (profile, keyName, defaultValue, isPrivate)
	if not profile.IsValid(keyName) then
		avatarAccessControl.currentUser.Profile.AddKey keyName, defaultValue
		profile.keyAccess(keyName) = 0		' non-private
		getProfileKey = defaultValue
		isPrivate = false
	else
		getProfileKey = profile.keyValue(keyName)
		if profile.keyAccess(keyName) = 1 then
			isPrivate = true 
		else
			isPrivate = false 
		end if
	end if
end function

'===========================================
' getProfileValues
' Load avatar profile values into page elements, using default values for missing profile keys
sub getProfileValues
	if trim(theForm.avatarList.value) = defaultAvatarName then exit sub

	dim n, profile, gender, isPrivate
	set profile = avatarAccessControl.currentUser.Profile

	' get the text values
	theForm.txtRealName.value = getProfileKey (profile, "Real name", "", isPrivate)
	theForm.chkRealName.status = isPrivate
	theForm.txtWhereFrom.value = getProfileKey (profile, "Where from", "", isPrivate)
	theForm.chkWhereFrom.status = isPrivate
	theForm.txtEMail.value = getProfileKey (profile, "E-Mail alias", "", isPrivate)
	theForm.chkEMail.status = isPrivate
	theForm.txtComment.value = getProfileKey (profile, "Quote", "", isPrivate)
	theForm.chkComment.status = isPrivate

	' get the gender checkbox selection
	gender = getProfileKey (profile, "Gender", "", isPrivate)
	theForm.sexMale.status = (gender = "male")
	theForm.sexFemale.status = (gender = "female")
end sub

'===========================================
' setProfileKey
' Set an avatar profile key value and access, adding the key if missing
sub setProfileKey (profile, keyName, keyValue, isPrivate)
	if profile.IsValid(keyName) then 
		profile.keyValue(keyName) = keyValue
	else
		profile.AddKey keyName, keyValue
	end if
	if isPrivate then 
		profile.keyAccess(keyName) = 1
	else
		profile.keyAccess(keyName) = 0
	end if
end sub

'===========================================
' saveProfileValues
' Save all avatar profile key values from page elements
sub saveProfileValues
	dim profile, pfList
	set profile = avatarAccessControl.currentUser.profile
	setProfileKey profile, "Gender", getGender, false
	setProfileKey profile, "Real name", theForm.txtRealName.value, theForm.chkRealName.status
	setProfileKey profile, "Where from", theForm.txtWhereFrom.value, theForm.chkWhereFrom.status
	setProfileKey profile, "E-Mail alias", theForm.txtEMail.value, theForm.chkEMail.status
	setProfileKey profile, "Quote", theForm.txtComment.value, theForm.chkComment.status
	if profile.isValid("FriendsPending") then 
		if isObject(profile.keyvalue("FriendsPending")) then
			set pfList = profile.keyvalue("FriendsPending")
			pfList.RemoveAll
			profile.keyvalue("FriendsPending") = pfList
		end if
	end if
end sub

sub document_OnSelectStart
	window.event.returnValue = (window.event.srcElement.tagName = "INPUT" or window.event.srcElement.id = "txtComment")
end sub

</script>
</head>
<body style="background-color:#090B82;">
  <form id=theForm action=Login.asp method=post>
	<!-- write various ASP parameters to HTML so client-side script can read them -->
	<input type=hidden id="clientPath" name="clientPath" value="<%=request("clientPath")%>">
	<input type=hidden id="hidFormMode" name="hidFormMode" value="<%=formMode%>">
	<input type=hidden id="hidWorldLocation" name="hidWorldLocation" value="<%=worldLocation%>">
	<input type=hidden id="hidWorldCount" name="hidWorldCount" value="<%=worldCount%>">
	<input type=hidden id="hidUsername" name="hidUsername" value="<%=username%>">
	<div id="pseudoBackground" style="position:absolute;top:46;left:170;text-align:right">
		<img src="../images/bkgLogin.gif">
	</div>
	<img src="../images/loginWelcome.gif" style="position:absolute;left:240;top:10;">
	<hr size=1 style="position:absolute;left:25;top:35;width:445;color:white;">

	<div id="errMsg" class="vText" style="position:absolute;top:45;left:50;width:350;height:15;color:crimson;background:white;text-align:center;
		font-weight:bold;display:none;"></div>

	<div class="vLabel" style="position:absolute;left:10;top:64;">
		<div class="vLabel" style="font-size:12;font-style:italic;font-weight:bold;color:white;position:relative;left:18;top:1;">General Information (required)</div>
		<table class="LoginTextLight" width="310" style="position:absolute;top:20">
			<tr><td width="125">Connect to world:</td>
				<td><select id="worldNum" name="worldNum" class="vInput" style="position:relative;top:2;width:40;">
					</select>
				</td></tr>
			<tr><td>Your Nickname:</td>
				<td>
					<select id="avatarList" name="avatarList" class="vInput" style="position:relative;top:2;width:100;">
						<option>&nbsp;</option>
					</select>&nbsp;
					<button id=btnDelete style="position:relative;top:4;width:48;" onclick=OnDeleteAvatar>Delete</button>
				</td></tr>
			<tr><td>Your Password:</td><td><input type="password" id="txtPassword" name="txtPassword" class="vText" maxlength="20" style="width:150;"></td></tr>
			<tr><td colspan=2>Please choose one:&nbsp;&nbsp;<span class="LoginTextLight"><input type="radio" id="sexMale" name="sex" value="male"><label for="sexMale">&nbsp;Male</label>
				&nbsp;&nbsp;&nbsp;&nbsp;<input type="radio" id="sexFemale" name="sex" value="female"><label for="sexFemale">&nbsp;Female</label></span></td></tr>
		</table>
	</div>


	<div class="vLabel" style="position:absolute;left:18;top:200;">
		<div class="vLabel" style="font-size:12;font-style:italic;font-weight:bold;color:white;position:relative;left:18; top:1;">Personal Information (optional)</div>
		<div class="LoginTextSmall" style="position:absolute;left:306;top:12;width:100;"><span style="font-family:webdings;font-size:12pt;">a</span>Private</div>
		<table class="LoginTextLight" width="330" style="position:absolute;top:25">
			<tr><td width="100">Real Name:</td><td><input type="text" id="txtRealName" class="vtext" maxlength="30" style="width:163;">
				&nbsp;<input type="checkbox" id="chkRealName"></td></tr>
			<tr><td>Where you're from:</td><td><input type="text" id="txtWhereFrom" class="vtext" maxlength="30" style="width:163;">
				&nbsp;<input type="checkbox" id="chkWhereFrom"></td></tr>
			<tr><td>E-Mail alias:</td><td><input type="text" id="txtEMail" class="vtext" maxlength="100" style="width:163;">
				&nbsp;<input type="checkbox" id="chkEMail"></td></tr>
			<tr><td>Comment:</td><td><textarea id="txtComment" class="vtext" rows="2" cols="28" style="width:163;">This is my first time here!</textarea>
				&nbsp;<input type="checkbox" id="chkComment"></td></tr>
		</table>
	</div>

	<img src="../images/go.gif" id=btnGo onclick=GoClick
		style="position:absolute; top:160; left:322; cursor:hand;">

	<div id=btnHelp class="LoginTextLight" onclick=helpClick() style="position:absolute;top:345;left:20;color:white;text-align:left;">Help&nbsp;
	<img src="../images/help.gif" style="position:absolute;"></div>

	<div id="copyright" class="vText" style="position:absolute;top:350;left:135;width:350;height:15;color:#8BACB3;text-align:right;">
	&#169;2000 Microsoft Corporation. All rights reserved.</div>
  </form>
  <iframe id=hidFrame style="position:absolute;top:200;left:0;height:180;width:400;display:none"></iframe>
</body>
</html>

<%
end if
%>
